package SBV::Constants;
#------------------------------------------------+
#    [APM] This moudle is generated by amp.pl    |
#    [APM] Creat time: 2013-05-13 16:40:36       |
#------------------------------------------------+
=pod

=head1 Name

SBV::Constants -- Constants for SBV

=head1 Synopsis

This module is not meant to be used directly

=head1 Feedback

Author: Peng Ai
Email:  aipeng0520@163.com

=head1 Version

Version history

=head2 v1.0

Date: 2013-05-13 16:40:36

=cut


use strict;
use warnings;

use base 'Exporter';

our $APP_NAME   = 'SBV';

our $DEG2RAD    = 0.0174532925;
our $RAD2DEG    = 57.29577951;
our $DEGRANGE   = 360;
our $PI_HALF    = 1.570796327;
our $PI         = 3.141592654;
our $TWOPI      = 6.283185307;

our $SQRT2      = 1.414213562;
our $SQRT3      = 1.732050808;
our $SQRT3_HALF = 0.866025404;

our @RAINBOW = ("#f00","#0f0","#0ff");

our $SEP = "[\,\t]";

our @EXPORT = qw($APP_NAME 
$DEG2RAD $RAD2DEG $DEGRANGE $PI_HALF $PI $TWOPI 
$SQRT2 $SQRT3 $SQRT3_HALF @RAINBOW $SEP);
