package SBV::DATA::Fasta;
#------------------------------------------------+
#    [APM] This moudle is generated by amp.pl    |
#    [APM] Created time: 2014-02-20 11:02:31     |
#------------------------------------------------+
=pod

=head1 Name

SBV::DATA::Fasta

=head1 Synopsis

This module is not meant to be used directly

=head1 Feedback

Author: Peng Ai
Email:  aipeng0520@163.com

=head1 Version

Version history

=head2 v1.0

Date: 2014-02-20 11:02:31

=cut


use strict;
use warnings;
require Exporter;

use FindBin;
use lib "$FindBin::RealBin";
use lib "$FindBin::RealBin/lib";
use lib "$FindBin::RealBin/../";
use lib "$FindBin::RealBin/../lib";

sub read_fasta_file
{
	my $file = shift;
	my $res;

	open FH,$file or die "can't open file $!";
	$/ = ">";
	
	<FH>;
	my $str = <FH>;
	my ($name,$seq) = split /\n/ , $str , 2;
	$seq =~ s/[\n\r]//g;
	$name = $1 if ($name =~ /^(\S+)/);
	my $len = length $seq;
	$/ = "\n";
	close FH;
	
	$res->{name} = $name;
	$res->{length} = $len;
	$res->{seq} = $seq;

	return $res;
}

